deploy:
  task:
    - git:
        repo: https://github.com/rukibhamz/National-Depository-of-Treaties/
        branch: dev
        destination: public_html/treaty
  exclude:
    - .cpanel.yml
    - .git
  post-deploy:
    - chmod -R 755 public_html/treaty
